<?php
/**
 * The template for displaying product content within loops.
 * The actual card markup is generated by the woocommerce_before_shop_loop_item,
 * woocommerce_shop_loop_item_title, and woocommerce_after_shop_loop_item hooks
 * registered in inc/woocommerce.php. This file exists to satisfy the
 * wc_get_template_part( 'content', 'product' ) call.
 *
 * @package TFG
 */

if ( ! defined( 'ABSPATH' ) ) exit;

global $product;

// Ensure visibility.
if ( empty( $product ) || ! $product->is_visible() ) {
	return;
}

/**
 * Hook: woocommerce_before_shop_loop_item.
 *
 * @hooked tfg_woo_card_open - 10 (opens the <a> and media wrapper)
 */
do_action( 'woocommerce_before_shop_loop_item' );

/**
 * Hook: woocommerce_before_shop_loop_item_title.
 *
 * @hooked tfg_woo_card_thumb - 10
 */
do_action( 'woocommerce_before_shop_loop_item_title' );

/**
 * Hook: woocommerce_shop_loop_item_title.
 *
 * @hooked tfg_woo_card_body - 10 (renders meta, title, specs, price, cta)
 */
do_action( 'woocommerce_shop_loop_item_title' );

/**
 * Hook: woocommerce_after_shop_loop_item.
 *
 * @hooked tfg_woo_card_close - 10 (closes the <a>)
 */
do_action( 'woocommerce_after_shop_loop_item' );
